### ISSUE TITLE
Concerns about failed migrations being marked as applied

### ISSUE THREAD

**Issue by ryanrolds** [uptrace/go-clickhouse#25]
First, thank you for this package and specifically the migration logic (from Bun). That said, I have some concerns about failed migrations being marked as applied. I understand that this allows the rollback logic to be run, but I'm not sure if the desirability of that outweighs the risks. 

The major risk I'm worried about is another "up" being performed before the "rollback" and the failed migration being skipped. CI/CD pipelines and developers not aware of this behavior may try to apply the migrations again, like in the case of a timeout or transient error, and be surprised by the behavior. I would argue it violates the principle of least surprise and that the defacto standard is for a following "up" to try applying the failed migration again, not skipping it.

**Comment by vmihailenco** [comment]
It is pretty easy to create an option that will mark migration as applied *after* the migration completed successfully - see https://github.com/uptrace/go-clickhouse/blob/master/chmigrate/migrator.go#L152-L155 . Please send a PR if you are interested.

**Comment by ryanrolds** [comment]
On it.

**Comment by ryanrolds** [comment]
How do you want tests to be written? I don't see a mocking tool in the project, which I would need to make assertions that Migrator isn't trying to write to the ch_migrations table. Any objection to adding [gomock](https://github.com/golang/mock)?

**Comment by vmihailenco** [comment]
No objections, but for a such simple change I won't ask for a test.
