### ISSUE TITLE
ch: unsupported compression method: 0x00

### ISSUE THREAD

**Issue by yandooo** [uptrace/go-clickhouse#40]
With compression switched on client parser throws the following exception:

```
ch: unsupported compression method: 0x51
...
ch: unsupported compression method: 0x00
```
the hex number at the end of the error looks random

Disabling compression leads to reading timeout issues. 

```
clickhouse/clickhouse-server:22.6
```

This error doesn't happen consistently. Some queries do get through and are successfully processed.

**Comment by vmihailenco** [comment]
How can I reproduce this? https://stackoverflow.com/help/minimal-reproducible-example

**Comment by yandooo** [comment]
It is inconsistent. It is hard to catch. I tend to believe it's an internal network setup (the bridge between CH on k8s and jump box). What can be enabled as debug/trace statement for the library to troubleshoot?

**Comment by vmihailenco** [comment]
This should be improved in v0.3.0
