### ISSUE TITLE
Is there any way for custom serialization/deserialization? 

### ISSUE THREAD

**Issue by Termina1** [uptrace/go-clickhouse#48]
I want to use clickhouse decimal type is it possible somehow?

**Comment by vmihailenco** [comment]
No, you would have to [define a column](https://github.com/uptrace/go-clickhouse/blob/master/ch/chschema/column.go#L606-L650) and register it [here](https://github.com/uptrace/go-clickhouse/blob/master/ch/chschema/types.go#L77).

**Comment by Termina1** [comment]
Ok, thanks
