### ISSUE TITLE
unsupported ClickHouse type="Bool"

### ISSUE THREAD

**Issue by Mendes11** [uptrace/go-clickhouse#49]
So, trying this lib but it appears that you missed implementing the conversion from `BOOLEAN` field to a valid golang `bool`?

Reproduction is to create a table such as: 

```sql
CREATE TABLE IF NOT EXISTS test (
    id VARCHAR,
    flag BOOLEAN
)
...
```

**Comment by vmihailenco** [comment]
Should be supported in v0.3.0
