### ISSUE TITLE
Go `[]byte` types mapped to `,type:LowCardinality(String)` yields `<[]uint8 value>` in query results

### ISSUE THREAD

**Issue by jdef** [uptrace/go-clickhouse#53]
given:
```
type Model struct {
...
  foo []byte `ch:",type:LowCardinality(String)"`
}
```
.. and then using the fluent table creation + query mechanism(s) of this library, the resulting data (when `foo` is queried) shows as `<[]uint8 value>` instead of the actual string-ish data that was intended for insertion.

**Comment by vmihailenco** [comment]
The solution for now is to use `string` instead of `[]byte`.
