### ISSUE TITLE
import package error

### ISSUE THREAD

**Issue by An-uking** [uptrace/go-clickhouse#6]
go: finding module for package github.com/uptrace/go-clickhouse/ch
go: found github.com/uptrace/go-clickhouse/ch in github.com/uptrace/go-clickhouse/ch v0.0.0-20220308124651-82a5d8d72ef7
go: downloading github.com/uptrace/go-clickhouse/chdebug v0.0.0-00010101000000-000000000000
	github.com/uptrace/go-clickhouse/ch tested by
	github.com/uptrace/go-clickhouse/ch.test imports
	github.com/uptrace/go-clickhouse/chdebug: github.com/uptrace/go-clickhouse/chdebug@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

**Comment by vmihailenco** [comment]
You can fix this by removing `github.com/uptrace/go-clickhouse/ch` from go.mod and running:

```shell
go get github.com/uptrace/go-clickhouse
```

Not sure how to remove `github.com/uptrace/go-clickhouse/ch` from go cache...
