### ISSUE TITLE
Cannot see VALUES when debugging INSERT queries

### ISSUE THREAD

**Issue by vinay2897** [uptrace/go-clickhouse#67]
Is there a way to see the entire INSERT query that was executed. Currently it shows only upto VALUES

![image](https://github.com/uptrace/go-clickhouse/assets/35741093/c4ab9787-a52f-495c-adaa-5e23ceef7470)

**Comment by vmihailenco** [comment]
go-clickhouse use the binary CH format so `VALUES` are not encoded with SQL format. Nothing we can do here.
